azure_devops:
  api_url: https://dev.azure.com
  auth_type: token
  credentials:
    personal_access_token: ''
  enabled: false
  organization: ''
bitbucket:
  api_url: https://api.bitbucket.org/2.0
  auth_type: token
  credentials:
    app_password: gAAAAABpfgf8n18DwNJoKZLImRCK02MSKVpJn7i4ZO6bRgR8guy4ScHNw_oWa2kiVVo2GPH9xjCiwLaZD3E_MQhWNyaACo2tjdif0oLCJ5E3KYLtkRJDs6SrX9JbFGpRF1sqf1F1HSWZGKLvc8Sa3njXe7pDjFHLVUdi9VXSoAHY0deQJmhotshpR7vzAup4256FCnfPrDKS5qNG_XcItUhnpmtwpJ1IwUxUT3AAnKyCn5E9_WXoKslLwyfCNpnLgSZkGzV3Y-M1tGMjLFCiGC4sTFBMksAobqad0VohCePwlUi3fTOC_QrKJeTpXo4YUkGCH079V4u9MfHQ0dAmThMKL8cp91t9Vw==
    client_id: ''
    client_secret: ''
    ssh_key_path: ''
    ssh_passphrase: ''
    username: ammarmahmoud1996
  enabled: true
clone:
  default_directory: ./projects
  depth: 0
  shallow_clone: false
  timeout: 300
git:
  auto_commit: true
  commit_message_template: 'AI Orchestrator: {action} - {timestamp}'
  default_branch: main
  user:
    email: ai-orchestrator@example.com
    name: AI Orchestrator
github:
  api_url: https://api.github.com
  auth_type: token
  credentials:
    client_id: ''
    client_secret: ''
    ssh_key_path: ''
    ssh_passphrase: ''
    token: gAAAAABpfgf8JchmnhBDf4tXllu58__0aYz24OYVLfiL_yN0LMoinFUIr5ISqcJP-DBZGPlGFRJ2Zai74CU7rmWGfO1GJFGC0jC7PBEi7h8jG1LZTrVHeVxP7sPKZYokNpf_Qa7pEmEi
    username: calipso_777
  enabled: true
gitlab:
  api_url: https://gitlab.com/api/v4
  auth_type: token
  credentials:
    client_id: ''
    client_secret: ''
    ssh_key_path: ''
    ssh_passphrase: ''
    token: gAAAAABpfgf8B39RRbXa1EK1obI8vKjfC4OFZdkcrnHmMYDeg9hy6bF2AO7fjbCSd8I2iyojQIiNGVDBQGW1hBYBB6oCU7VdjkRn-Qeec7rGyL68mPBWGyMlfVwTWES13QDsdLFRxNQ7X1WvUJnPW96h9C2lfFmn1g==
    username: ammarmahmoud1996
  enabled: true
security:
  credential_storage: encrypted_file
  encrypt_credentials: true
  encryption_key_env: GIT_ENCRYPTION_KEY
webhooks:
  enabled: false
  port: 9000
  secret: ''
